#' @importFrom data.tree as.Node ToDataFrameTable SetNodeStyle
#' @importFrom DiagrammeRsvg export_svg
#' @importFrom rsvg rsvg_pdf

generaPleasantTree<-function(cTree,w,h,r, colori,
                             filePath, titleOfTree="Conditional inference tree"){
  
  #plot binary tree generated by party package
 
  type<-"extended"
  nodoInterno<-node_inner(ctreeobj=cTree, digits = 3, abbreviate = FALSE,
             fill = "white", pval = TRUE, id = TRUE)
  nodoTerminale<-node_barplot(ctreeobj=cTree, col = "white", fill = colori, beside = TRUE,
                              ymax = NULL, ylines = NULL, widths = 1, gap = NULL, 
                              reverse = FALSE, id = TRUE)
  edges<-edge_simple(treeobj=cTree, digits = 2, abbreviate = FALSE)
  
  tiff(filePath, width=w, height=h,res=r)
  plot(x=cTree, main = titleOfTree, type = type,
       terminal_panel =  nodoTerminale, tp_args = list(),
       inner_panel = nodoInterno, ip_args = list(),
       edge_panel = edges, ep_args = list(),
       drop_terminal = (type[1] == "extended"),
       tnex = (type[1] == "extended") + 1, newpage = TRUE,
       pop = TRUE)
  dev.off()
  
  #PLOT PATHS
  tree <- as.Node(cTree)
  df <- ToDataFrameTable(x=tree,
                         "pathString",
                         "label",
                         criterion = function(x) round(x$criterion$maxcriterion, 3),
                         statistic = function(x) round(max(x$criterion$statistic), 3)
  )
  subtree <- tree # Clone(tree$`2`)
  SetNodeStyle(subtree, 
               style = "filled,rounded", 
               shape = "box", 
               fillcolor = "GreenYellow", 
               fontname = "helvetica", 
               label = function(x) x$label,
               tooltip = function(x) round(x$criterion$maxcriterion, 3))
  newfilePath<-paste(sub(pattern=".tiff|.png|.jpg|.jpeg", replacement="", x=filePath, 
                         ignore.case = TRUE, perl = FALSE),"_paths.pdf", sep="")
  plot(subtree) %>% export_svg %>% charToRaw %>% rsvg_pdf(newfilePath)
  
}
